apiVersion: v1
kind: Namespace
metadata:
  labels:
    name: external-dns-operator
  name: external-dns-operator
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns-operator
  namespace: external-dns-operator
  labels:
    name: external-dns-operator
spec:
  selector:
    matchLabels:
      name: external-dns-operator
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: external-dns-operator
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
      - name: external-dns-operator
        image: quay.io/openshift/origin-external-dns-operator:latest
        args:
        - --metrics-bind-address=127.0.0.1:8080
        - --operator-namespace=$(OPERATOR_NAMESPACE)
        - --operand-namespace=$(OPERATOR_NAMESPACE)
        - --externaldns-image=$(RELATED_IMAGE_EXTERNAL_DNS)
        - --trusted-ca-configmap=$(TRUSTED_CA_CONFIGMAP_NAME)
        env:
        - name: OPERATOR_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: RELATED_IMAGE_EXTERNAL_DNS
          value: k8s.gcr.io/external-dns/external-dns:v0.10.2
        - name: TRUSTED_CA_CONFIGMAP_NAME
        securityContext:
          allowPrivilegeEscalation: false
        resources:
          requests:
            cpu: 100m
            memory: 30Mi
      serviceAccountName: external-dns-operator
