apiVersion: v1
kind: Namespace
metadata:
  labels:
    name: external-dns-operator
  name: external-dns-operator
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns-operator
  namespace: external-dns-operator
  labels:
    name: external-dns-operator
spec:
  selector:
    matchLabels:
      name: external-dns-operator
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        name: external-dns-operator
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
      - name: external-dns-operator
        image: quay.io/openshift/origin-external-dns-operator:latest
        args:
        - --metrics-bind-address=127.0.0.1:8080
        - --operator-namespace=$(OPERATOR_NAMESPACE)
        - --operand-namespace=$(OPERATOR_NAMESPACE)
        - --externaldns-image=$(RELATED_IMAGE_EXTERNAL_DNS)
        - --trusted-ca-configmap=$(TRUSTED_CA_CONFIGMAP_NAME)
        - --leader-elect
        - --webhook-disable-http2
        env:
        - name: OPERATOR_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: RELATED_IMAGE_EXTERNAL_DNS
          # openshift/external-dns commit: 0e095a3db5ae9518a1744dd85d3f7ed2e359768d
          value: quay.io/external-dns-operator/external-dns@sha256:6fa3afebbc99926163d4c827a638473e106e6589e9f3d3d3accd3e426693f04f
        - name: TRUSTED_CA_CONFIGMAP_NAME
        securityContext:
          capabilities:
            drop:
            - "ALL"
          privileged: false
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          seccompProfile:
            type: "RuntimeDefault"
        resources:
          requests:
            cpu: 100m
            memory: 30Mi
      serviceAccountName: external-dns-operator
